### ISSUE TITLE
Mort ?

### ISSUE THREAD

**Issue by Narno** [wo0dyn/magento-web-debug-toolbar#1]
Est-ce que le projet est définitivement mort ?

**Comment by wo0dyn** [comment]
@Narno › pfff, j'ai honte, toutes mes excuses :confused:

**Comment by Narno** [comment]
Pas de soucis, je connais ça aussi ! Je faisais juste du tri dans toutes mes issues encore ouvertes :-)

**Comment by wo0dyn** [comment]
@Narno › merci pour ta compréhension ; je vais supprimer le repo, car 

1. le code est obsolète (j'imagine)
2. je ne le maintiendrai pas dans tous les cas

De mémoire (mais alors ça remonte à loin hein !), je crois qu'il y a des extensions qui font le job très bien. :wink:
